import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const money = (paise) => `₹${(Number(paise || 0) / 100).toLocaleString('en-IN')}`;
async function api(path, options) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const text = await response.text(); let body; try { body = text ? JSON.parse(text) : {}; } catch { body = { error: text || `Request failed (${response.status})` }; } if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }

function App() {
  const [invoices, setInvoices] = useState([]); const [audit, setAudit] = useState([]); const [metrics, setMetrics] = useState({}); const [reply, setReply] = useState(''); const [selected, setSelected] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const [nextInvoices, nextAudit, nextMetrics] = await Promise.all([api('/api/invoices'), api('/api/audit'), api('/api/metrics')]); if (!Array.isArray(nextInvoices)) throw new Error('API returned invalid invoice data. Check the Vercel function routing.'); setInvoices(nextInvoices); setSelected((current) => current || nextInvoices[0]?.id || ''); setAudit(Array.isArray(nextAudit) ? nextAudit : []); setMetrics(nextMetrics && typeof nextMetrics === 'object' ? nextMetrics : {}); } catch (error) { setNotice(`Backend unavailable. ${error.message}`); } };
  useEffect(() => { refresh(); }, []);
  const run = async (operation, success) => { setBusy(true); try { await operation(); setNotice(success); await refresh(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const reset = () => run(() => api('/api/seed/reset', { method: 'POST' }), 'Database reset. Import the CSV to begin.');
  const importSample = () => run(async () => { const csv = await fetch('/api/invoices/sample').then((r) => r.text()); await api('/api/invoices/bulk', { method: 'POST', headers: { 'Content-Type': 'text/csv' }, body: csv }); }, '100 synthetic invoices imported.');
  const uploadCsv = (event) => { const file = event.target.files[0]; if (!file) return; run(() => file.text().then((csv) => api('/api/invoices/bulk', { method: 'POST', headers: { 'Content-Type': 'text/csv' }, body: csv })), `${file.name} imported successfully.`); event.target.value = ''; };
  const recover = () => run(() => api('/api/recover', { method: 'POST' }), 'Recovery batch completed.');
  const promise = async (event) => { event.preventDefault(); await run(() => api('/api/promises', { method: 'POST', body: JSON.stringify({ invoice_id: selected, raw_text: reply, today: '2026-09-05' }) }), 'Promise recorded with date and confidence.'); setReply(''); };
  return <main><header><div><p className="eyebrow">RAZORPAY AI BUILDATHON / TRACK 03</p><h1>Recovery control room</h1><p className="sub">Explainable receivables recovery with a hard compliance gate.</p></div><div className="actions"><button disabled={busy} onClick={reset}>Reset demo</button><button disabled={busy} onClick={importSample}>Load sample</button><label className="button" style={{ display: 'inline-block', border: '1px solid #c5d0c4', background: '#f8faf6', color: '#263329', padding: '11px 15px', borderRadius: 4, font: '700 12px Manrope', cursor: 'pointer' }}><input style={{ display: 'none' }} type="file" accept=".csv,text/csv" onChange={uploadCsv} />Upload CSV</label><button className="primary" disabled={busy} onClick={recover}>Run recovery</button></div></header>
    {notice && <div className="notice">{notice}</div>}
    <section className="metrics"><Metric label="At risk" value={money(metrics.amountAtRisk)} /><Metric label="Recovered" value={money(metrics.amountRecovered)} /><Metric label="Recovery rate" value={`${metrics.recoveryRate || 0}%`} /><Metric label="Escalations" value={metrics.escalationCount || 0} /><Metric label="Broken promises" value={`${metrics.brokenPromiseRate || 0}%`} /></section>
    <section className="grid"><div className="panel wide"><div className="panel-head"><h2>Invoice queue</h2><span>{invoices.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Amount</th><th>Age</th><th>Risk</th><th>Status</th></tr></thead><tbody>{invoices.slice(0, 25).map((invoice) => <tr key={invoice.id}><td className="mono">{invoice.id}</td><td>{invoice.customer_name}</td><td>{money(invoice.amount)}</td><td>{invoice.days_overdue}d <small>{invoice.bucket}</small></td><td><b>{invoice.risk_score}</b></td><td><span className={`pill ${invoice.dnc_flag ? 'red' : invoice.status !== 'open' ? 'gray' : 'green'}`}>{invoice.dnc_flag ? 'DNC' : invoice.status}</span></td></tr>)}</tbody></table></div></div>
      <div className="panel"><div className="panel-head"><h2>Promise simulator</h2></div><form onSubmit={promise}><label>Invoice<select value={selected} onChange={(e) => setSelected(e.target.value)} disabled={!invoices.length}>{invoices.slice(0, 30).map((i) => <option key={i.id}>{i.id}</option>)}</select></label><label>Customer reply<textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="will pay by the 20th" required /></label><button className="primary full" disabled={!selected || busy}>Log promise</button></form><p className="hint">The parser stores the raw reply, date, confidence, and status. Import invoices before logging a promise.</p></div>
      <div className="panel wide"><div className="panel-head"><h2>Immutable audit trail</h2><a href="/api/audit/export">Export CSV ↗</a></div><div className="audit">{audit.slice(0, 12).map((entry) => <div className="audit-row" key={entry.id}><span className="mono">{entry.invoice_id || 'batch'}</span><span className={`pill ${entry.action.startsWith('blocked') ? 'red' : 'green'}`}>{entry.action}</span><span>{entry.reasoning}</span></div>)}</div></div></section>
  </main>;
}
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
createRoot(document.getElementById('root')).render(<App />);