require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('node:path');
require('./db');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/invoices', require('./routes/invoices'));
app.use('/api/recover', require('./routes/recover'));
app.use('/api/promises', require('./routes/promises'));
app.use('/api/metrics', require('./routes/metrics'));
app.use('/api/audit', require('./routes/audit'));
app.use('/api/seed/reset', require('./seed/reset'));
app.use(express.static(path.join(__dirname, '..', 'client', 'dist')));
app.use((error, req, res, next) => { console.error(error); res.status(500).json({ error: error.message }); });
const port = Number(process.env.PORT || 5000);
if (require.main === module) app.listen(port, () => console.log(`Revenue recovery API listening on http://localhost:${port}`));
module.exports = app;